// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    01tabBar: typeof import('./src/components/tab-bar/01tab-bar.vue')['default']
    '02tabBar 手动封装，并抽离数据': typeof import('./src/components/tab-bar/02tab-bar 手动封装，并抽离数据.vue')['default']
    '03tabBar Vant封装，并修改子组件样式': typeof import('./src/components/tab-bar/03tab-bar Vant封装，并修改子组件样式.vue')['default']
    '手动封装，并抽离数据': typeof import('./src/components/tab-bar/tab-bar 手动封装，并抽离数据.vue')['default']
    '手动封装，并抽离数据02': typeof import('./src/components/tab-bar/tab-bar 手动封装，并抽离数据02.vue')['default']
    copy: typeof import('./src/components/tab-bar/tab-bar copy.vue')['default']
    DetailSection: typeof import('./src/components/detail-section/detail-section.vue')['default']
    HouseItemV3: typeof import('./src/components/house-item-v3/house-item-v3.vue')['default']
    HouseItemV9: typeof import('./src/components/house-item-v9/house-item-v9.vue')['default']
    Loading: typeof import('./src/components/loading/loading.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/search-bar/search-bar.vue')['default']
    TabBar: typeof import('./src/components/tab-bar/tab-bar.vue')['default']
    TabBar_01: typeof import('./src/components/tab-bar/tab-bar_01.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCalendar: typeof import('vant/es')['Calendar']
    VanCell: typeof import('vant/es')['Cell']
    VanIcon: typeof import('vant/es')['Icon']
    VanIndexAnchor: typeof import('vant/es')['IndexAnchor']
    VanIndexBar: typeof import('vant/es')['IndexBar']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanRate: typeof import('vant/es')['Rate']
    VanSearch: typeof import('vant/es')['Search']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    'Vant封装，并修改子组件样式': typeof import('./src/components/tab-bar/03tab-bar Vant封装，并修改子组件样式.vue')['default']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
  }
}
