// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    '手动封装，并抽离数据': typeof import('./src/components/tab-bar/tab-bar 手动封装，并抽离数据.vue')['default']
    '手动封装，并抽离数据02': typeof import('./src/components/tab-bar/tab-bar 手动封装，并抽离数据02.vue')['default']
    copy: typeof import('./src/components/tab-bar/tab-bar copy.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabBar: typeof import('./src/components/tab-bar/tab-bar.vue')['default']
    'TabBar 手动封装，并抽离数据02': typeof import('./src/components/tab-bar/tab-bar 手动封装，并抽离数据02.vue')['default']
    TabBar_01: typeof import('./src/components/tab-bar/tab-bar_01.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanRate: typeof import('vant/es')['Rate']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
  }
}
